CREATE DATABASE SPORTS_INFO;
USE SPORTS_INFO;
CREATE TABLE SPORTS_INFO(ID INT,PLAYERNAME varchar(20),PLAYER_NUM INT,STATE varchar(10),HIGHEST_SCORE INT,WICKETS INT,SCORE INT,MATCHES INT,COUNTRY varchar(10), TEAM VARCHAR(7));
 ALTER TABLE SPORTS_INFO  ADD COLUMN  INTERNATIONAL_RUNS INT;
DESC SPORTS_INFO; 
SELECT *FROM SPORTS_INFO ;
ALTER TABLE SPORTS_INFO RENAME COLUMN PLAYERNAME to SPORTS_PLAYERNAME;
ALTER TABLE SPORTS_INFO RENAME COLUMN PLAYER_NUM to SPORTS_PLAYERNUM;
INSERT INTO SPORTS_INFO VALUES(1,'ROHIT',45,'MUMBAI',264,87,15001,229,'india','INDIAN',18988);
INSERT INTO SPORTS_INFO VALUES(2,'BABR',435,'KARACHI',274,490,15020,399,'pakistan','pak',1788);
INSERT INTO SPORTS_INFO VALUES(3,'GAYLE',145,'MUBARAK',94,490,19030,98,'WI','WI',17839);
INSERT INTO SPORTS_INFO VALUES(4,'WADE',495,'SYDNEY',48,90,18924,397,'AUSTRALIA','AUS',19488);
INSERT INTO SPORTS_INFO VALUES(5,'ABD',25,'MANDEO',47,78,28993,386,'SOTHAFRICA','SA',17858);
INSERT INTO SPORTS_INFO VALUES(6,'RANCHU',5,'BANKOO',84,83,28983,385,'ZIMBABE','ZIM',19868);
INSERT INTO SPORTS_INFO VALUES(7,'ROHITH',35,'MUCCI',41,82,128,384,'NL','NEPAL',17887);
INSERT INTO SPORTS_INFO VALUES(8,'DILSHAN',85,'COLUMBOO',24,190,15070,393,'SRILANKA','SL',19808);
INSERT INTO SPORTS_INFO VALUES(9,'COOK',11,'PETER',64,809,1508,32,'ENG','ENGLAND',17898);
INSERT INTO SPORTS_INFO VALUES(10,'POHIT',1,'MOMGII',264,80,1590,391,'MAA','MONGOSL',17898);

DELETE FROM SPORTS_INFO WHERE SPORTS_PLAYERNAME='ROHIT';
DELETE FROM SPORTS_INFO WHERE ID=5;

SELECT * FROM  SPORTS_INFO WHERE STATE='MUMABI' AND WICKETS =83 AND ID=3;
SELECT * FROM  SPORTS_INFO WHERE STATE='MUCCI' OR TEAM='AUS' OR ID=3;
SELECT * FROM  SPORTS_INFO WHERE STATE='KARACHI' OR TEAM='ZIM' OR ID=7;
SELECT* FROM SPORTS_INFO WHERE MATCHES IN(399,98,397);
SELECT* FROM SPORTS_INFO WHERE SPORTS_PLAYERNUM IN(435,5,35);
SELECT* FROM SPORTS_INFO WHERE MATCHES NOT IN(399,98,397);
SELECT* FROM SPORTS_INFO WHERE MATCHES NOT IN(435,5,35);

drop table SPORTS_INFO;


UPDATE,DELETE,WHERE,IN,AND,OR,OUT,BETWEEN


ORDEER BY;

SELECT * FROM SPORTS_INFO ORDER BY ID;
SELECT * FROM SPORTS_INFO ORDER BY ID DESC;


UPPER:

SELECT UPPER(SPORTS_PLAYERNAME) FROM SPORTS_INFO;

LOWER:

SELECT LOWER(SPORTS_PLAYERNUM) AS LOWER_CASE FROM SPORTS_INFO;


LIKE: PATTERN MATCHING

% :
INSTR,SUBSTR
SELECT * FROM SPORTS_INFO WHERE SPORTS_PLAYERNAME LIKE 'A%';

CONSTRAINTS:

1) NOT NULL:

CREATE TABLE grocery_info(id int,g_name varchar(30) not null,price decimal(5,2),created_at timestamp,modified_at timestamp);
SELECT* from grocery_info;
INSERT INTO grocery_info VALUES(1,'RICE',300.5,NOW(),NOW());
DROP TABLE grocery_info;

UNIQUE;

TASK:
DATABASE NAME: SEP_4TH.
CREATE 5 TABLES 15 COLUMS  WHILE CREATING TABLE.
APPLY NOT NULL AND UNIQUE FOR EACH COLUMN(ALL 15 COLUMNS).
INSERT  20 DATA FOR EACH TABLE.
TABLES:
LENSKART_INFO
DISTRICTS_INFO
STATE_INFO
COUNTRY_INFO
AIRLINES_INFO





Default:


create table pancard(




primary key;

create table library(id int primary key ,l_name  varchar(30));
















